### ISSUE TITLE
Any idea?

### ISSUE THREAD

**Issue by Masihhedayati** [CravingCrates/AnkiCollab-Plugin#3]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-13.2.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-03-01 04:19:33
Add-ons possibly involved: ⁨AnkiCollab - The free collaboration Platform⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/stevmq/Library/Application Support/Anki2/addons21/1957538407/main.py", line 262, in on_publish_button_clicked
    uuid = handle_export(deck_id, email)
  File "/Users/stevmq/Library/Application Support/Anki2/addons21/1957538407/import_export.py", line 174, in handle_export
    disambiguate_note_model_uuids(aqt.mw.col)
  File "/Users/stevmq/Library/Application Support/Anki2/addons21/1957538407/crowd_anki/utils/disambiguate_uuids.py", line 38, in disambiguate_note_model_uuids
    collection.models.save(model)
  File "anki.models", line 559, in save
  File "anki.models", line 542, in update
  File "anki._backend_generated", line 883, in add_or_update_notetype
  File "anki._backend", line 151, in _run_command
anki.errors.CardTypeError: Card template ⁨3⁩ in notetype '⁨AUTOPIMPER-Neuro Nucleus Pathway(v2)+⁩' has a problem.<br>See the preview for more information.

**Comment by CravingCrates** [comment]
Seems like there is an issue with the notetype 'AUTOPIMPER-Neuro Nucleus Pathway(v2)+⁩'. Not sure what's causing it. Can you check the preview for more information on what's wrong?

Or join the discord server and export 1 note with that card and send it to me. I'll try my best to find the issue and fix it!
